relativeURLs = true
title = "Gabriella Fleischman"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = "Ph.D. Candidate in Public Policy (Economics Track), Harvard University"
    logo = "gf_headshot.jpg" 
    
